# Generated by Django 3.0.6 on 2020-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptMonthlyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kvgs', models.UUIDField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('production_plan', models.FloatField(blank=True, null=True)),
                ('revenue_plan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rpt_monthly_plan',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rptoperators',
            options={'managed': False},
        ),
    ]
